<?php
function lang($lang)
{
  static $arr = array(
    '2SaniyeBekleyin'           => 'Please Wait Two Seconds',
    'LojistikOtomasyonu'        => 'Logistics System',
    // Ust
    'CikisYap'                  => 'Log out',
    'Profil'                    => 'Profile',
    // Sidebar
    'AnaSayfa'                  => 'Dashboard',
    'Kategoriler'               => 'categories',
    'Urunler'                   => 'Products',
    'Satislar'                  => 'Sales',
    'Raporlar'                  => 'Reports',
    'Kullanicilar'              => 'Users',
    // Giris
    'GirisYap'                  => 'Login',
    'KullaniciAdi'              => 'Username',
    'Sifre'                     => 'Password',
    'SifremiUnuttum'            => 'I forgot my password',
    'kullaniciAdiYadaSifreHata' => 'Username or Password is Incorrect. If you are a Passive User, you cannot login!!',
    'GirisSayfasinaGit'         => 'Go to Home Page',
    'SifreSifirla'              => 'Reset Password',
    'Ad'                        => 'First Name',
    'SoyAd'                     => 'Last Name',
    'Departman'                 => 'Department',
    // Kategoriler
    'KategoriEkle'              => 'Add a Category',
    'KategoriAra'               => 'Search a Category',
    'KategoriAdi'               => 'Category Name',
    'KategoriNo'                => 'Category No',
    'Kontrol'                   => 'Control',
    'Ekle'                      => 'Add',
    'Ara'                       => 'Search',
    'kategoriEklendi'           => ' Category Added',
    'degistir'                  => 'Update',
    'katSilindi'                => ' Category Deleted',
    'katGuncellendi'            => ' Category Uptaded',
    // Urunler
    'urunAra'                   => 'Add a Product',
    'urunAdi'                   => 'Product Name',
    'urunNo'                    => 'Product No',
    'depodaAdet'                => 'Product Quantity',
    'kategori'                  => 'Category',
    'depoyaGirmeTarihi'         => 'To Warehouse Insert Date',
    'tedarikci'                 => 'Supplier',
    'urunAdresi'                => 'Product Address',
    'adet'                      => 'Quantity',
    'alimFiyati'                => 'Purchase Price',
    'satimFiyati'               => 'Satım Fiyatı',
    'rafNo'                     => 'Shelf No',
    'sonucBulunmadi'            => 'There were no results',
    'UrunEklendi'               => ' Product Added',
    'urunSilindi'               => ' Product Deleted',
    'bitti'                     => 'finished',
          // Urunler Hatalari
    'fotoYuklenmedi'            => 'No Photo Uploaded',
    'fotoUzantiYok'             => 'Photo Extension Not Supported',
    'fotoBoyut10mbBuyukYok'     => 'Photo Size Shouldn\'t Be More Than 10MB',
    'urunAdiBosveya5tenfazlaYok'=> 'Product Name must not be blank or Character Number less than 5',
    'katYok'                    => 'Category Must Not Be Empty',
    'tedarikciBosYok'           => 'Supplier Must Not Be Empty',
    'uAdresiBosYok'             => 'Product Address Must Not Be Empty',
    'uAdetBos0HarfYok'          => 'Item Quantity Empty, Must Not Contain 0 or Letters',
    'uAlimBos0HarfYok'          => 'Product Purchase Price Must Not Contain Empty, 0 or Letters',
    'uSatimBos0HarfAlimAzYok'   => 'Item Selling Price Must Not Be Empty, 0, Letter or Less Than Purchase Price',
    'rafNoYok'                  => 'Shelf Number Shouldn\'t Be Empty',
    'urunGuncenlendi'           => ' Product Updated',
    'eklemeTarihi'              => 'Added Date',
    'ekleyen'                   => 'Submitted by',
    // Satislar
    'satisAra'                  => 'Search for Sales',
    'satisYap'                  => 'Make a Sale',
    'satilacakUrunNoGiriniz'    => 'Enter Item Number to be Sold',
    'urunBilgileri'             => 'Product Information',
    'satisBilgileri'            => 'Sales Information',
    'satilacakAdet'             => 'Quantity to be Sold',
    'hesapla'                   => 'Calculate',
    'toplam'                    => 'Total',
    'fazlaSatilamaz'            => ' No More Pieces Can Be Sold',
    'fiyattanDusukSatilamaz'    => ' Sold Under Price (Zarar Selling)',
    'alici'                     => 'Recipient Name',
    'SatisYapildi'              => ' Made a Sale',
    'aliciBos'                  => 'Recipient Must Not Be Empty',
    'satisIptalEdildi'          => ' Sale Canceled',
    'satisNo'                   => 'Sales No',
    'satilanAdet'               => 'Quantity Sold',
    'satisTarihi'               => 'Sale Date',
    'birineFiyat'               => 'Price for One',
    'satisiYapan'               => 'Seller',
    // Raporlar 
    'suTarihten'                => 'From the Date',
    'suTariheKadar'             => 'Until Date',
    'satislar'                  => ' Sales',
    'tarihten'                  => ' from ',
    'tariheKadar'               => ' Until Date',
    'lutfenGecerliTarihGiriniz' => 'Please Enter Valid Date',
    'toplamPara'                => 'Total Money',
    'toplamKar/Zarar'           => 'Total Profit/Loss',
    'Kar/Zarar'                 => 'Profit/Loss',
    'sonHafta'                  => 'Last Week',
    'sonAy'                     => 'Last Month',
    'son6Ay'                    => 'Last 6 Months',
    'sonYil'                    => 'Last Year',
    // kullanicilar
    'kullaniciAra'              => 'User Search',
    'kNo'                       => 'User ID',
    'kAdi'                      => 'Username',
    'kIsi'                      => 'Department',
    'aktifPasif'                => 'Active/passive',
    'sonGirisTarihi'            => 'Last Login Date',
    'aktif'                     => 'Active',
    'pasif'                     => 'passive',
    'ad'                        => 'First Name',
    'soyAd'                     => 'Last Name',
    'isi'                       => 'Department',
    'sifreTekrar'               => 'Password Repeat',
    'kullaniciEklendi'          => ' User Added',
    'yonetici'                  => 'Admin',
          // hatalar
    'AdiBosveya4tenfazlaYok'    => 'First Name must not be blank or Character Number less than 4',
    'sAdiBosveya4tenfazlaYok'   => 'Last Name must not be blank or Character Number less than 4',
    'kAdiBosveya5tenfazlaYok'   => 'Username must not be blank or Character Number less than 4',
    'departmanBos'              => 'Department Shouldn\'t Be Empty',
    'sifreEsitYok'              => 'Password Must Be Equal',
    'buKDahaOnceKullanildi'     => 'This Username Has Been Used Before',
    'kullaniciSilindi'          => ' User Deleted',
    'kullaniciGuncellendi'      => ' User Updadet',
    // Anasayfa
    'gununSatisToplamiTl'       => 'Today\'s Sales Total TL',
    'depodaUrunSayisi'          => 'Number of Products in Warehouse',
    'satilanUrunSayisi'         => 'Number of Products Sold Todayı',
    'enCokSatilanlar'           => 'Best seller',
    'sonSatislar'               => 'Recent Sales',
    'yeniEklenenUrunler'        => 'Newly Added Products',
  );
  return $arr[$lang];
}
