<?php
function lang($lang)
{
  static $arr = array(
    '2SaniyeBekleyin'           => 'Lütfen İki Saniye Bekleyin',
    'LojistikOtomasyonu'        => 'Lojistik Otomasyonu',
    // Ust
    'CikisYap'                  => 'Çıkış Yap',
    'Profil'                    => 'Profil',
    // Sidebar
    'AnaSayfa'                  => 'Ana Sayfa',
    'Kategoriler'               => 'Kategoriler',
    'Urunler'                   => 'Ürünler',
    'Satislar'                  => 'Satışlar',
    'Raporlar'                  => 'Raporlar',
    'Kullanicilar'              => 'Kullanıcılar',
    // Giris
    'GirisYap'                  => 'Giriş Yap',
    'KullaniciAdi'              => 'Kullanıcı Adı',
    'Sifre'                     => 'Şifre',
    'SifremiUnuttum'            => 'Şifremi Unuttum',
    'kullaniciAdiYadaSifreHata' => 'Kullanıcı Adı Yada Şifre Hatalıdır, Pasif Kullanıcı iseniz giriş yapamazsınız!!',
    'GirisSayfasinaGit'         => 'Giriş Sayfasına Git',
    'SifreSifirla'              => 'Şifre Sıfırla',
    'Ad'                        => 'Ad',
    'SoyAd'                     => 'Soy Ad',
    'Departman'                 => 'Departman',
    // Kategoriler
    'KategoriEkle'              => 'Kategori Ekle',
    'KategoriAra'               => 'Kategori Ara',
    'KategoriAdi'               => 'Kategori Adı',
    'KategoriNo'                => 'Kategori No',
    'Kontrol'                   => 'Kontrol',
    'Ekle'                      => 'Ekle',
    'Ara'                       => 'Ara',
    'kategoriEklendi'           => ' Kategori Eklendi',
    'degistir'                  => 'Güncelle',
    'katSilindi'                => ' Kategori Silindi',
    'katGuncellendi'            => ' Kategori Güncellendi',
    // Urunler
    'urunAra'                   => 'Ürün Ara',
    'urunAdi'                   => 'Ürün Adı',
    'urunNo'                    => 'Ürün No',
    'depodaAdet'                => 'Ürün Adet',
    'kategori'                  => 'Kategori',
    'depoyaGirmeTarihi'         => 'Depoya Girme Tarihi',
    'tedarikci'                 => 'Tedarikçi',
    'urunAdresi'                => 'Ürün Adresi',
    'adet'                      => 'Adet',
    'alimFiyati'                => 'Alım Fiyatı',
    'satimFiyati'               => 'Satım Fiyatı',
    'rafNo'                     => 'Raf No',
    'sonucBulunmadi'            => 'Sonuç Bulunmadı',
    'UrunEklendi'               => ' Ürün Eklendi',
    'urunSilindi'               => ' Ürün Silindi',
    'bitti'                     => 'Bitti',
          // Urunler Hatalari
    'fotoYuklenmedi'            => 'Fotoğraf Yüklenmedi',
    'fotoUzantiYok'             => 'Fotoğraf Üzantısı Desteklenmemektedir',
    'fotoBoyut10mbBuyukYok'     => 'FotoğrafBoyutu 10MB\'ten Büyük Olmamalı',
    'urunAdiBosveya5tenfazlaYok'=> 'Ürün Adı boş veya Karakter Sayısı 5\'ten Az olmamalı',
    'katYok'                    => 'Kategori Boş Olmamalı',
    'tedarikciBosYok'           => 'Tedarikçi Boş Olmamalı',
    'uAdresiBosYok'             => 'Ürün Adresi Boş Olmamalı',
    'uAdetBos0HarfYok'          => 'Ürün Adet Boş, 0 veya Harf İçermemeli',
    'uAlimBos0HarfYok'          => 'Ürün Alım Fiyatı Bos, 0 veya Harf İçermemeli',
    'uSatimBos0HarfAlimAzYok'   => 'Ürün Satım Fiyatı Bos, 0, Harf veya Alım Fiyatından Az Olmamalı',
    'rafNoYok'                  => 'Raf No Bos Olmamalı',
    'urunGuncenlendi'           => ' Ürün Güncellendi',
    'eklemeTarihi'              => 'Ekleme Tarihi',
    'ekleyen'                   => 'Ekleyen',
    // Satislar
    'satisAra'                  => 'Satış Ara',
    'satisYap'                  => 'Satış Yap',
    'satilacakUrunNoGiriniz'    => 'Satılacak Ürün Numarasını Giriniz',
    'urunBilgileri'             => 'Ürün Bilgileri',
    'satisBilgileri'            => 'Satış Bilgileri',
    'satilacakAdet'             => 'Satılacak Adet',
    'hesapla'                   => 'Hesapla',
    'toplam'                    => 'Toplam',
    'fazlaSatilamaz'            => ' Fazla Adet Satılamaz',
    'fiyattanDusukSatilamaz'    => ' Fiyattan Düşük Satıldı ( Zararlı Satış )',
    'alici'                     => 'Alıcı Adı',
    'SatisYapildi'              => ' Satış Yapıdı',
    'aliciBos'                  => 'Alıcı Boş Olmamalı',
    'satisIptalEdildi'          => ' Satış İptal Edildi',
    'satisNo'                   => 'Satış No',
    'satilanAdet'               => 'Satılan Adet',
    'satisTarihi'               => 'Satış Tarihi',
    'birineFiyat'               => 'Birine Fiyat',
    'satisiYapan'               => 'Satışı Yapan',
    // Raporlar 
    'suTarihten'                => 'Şu Tarihten',
    'suTariheKadar'             => 'Şu Tarihe Kadar',
    'satislar'                  => ' Satışlar',
    'tarihten'                  => ' Tarihten ',
    'tariheKadar'               => ' Tarihe Kadar',
    'lutfenGecerliTarihGiriniz' => 'Lütfen Geçerli Tarih Giriniz',
    'toplamPara'                => 'Toplam Para',
    'toplamKar/Zarar'           => 'Toplam Kar/Zarar',
    'Kar/Zarar'                 => 'Kar/Zara',
    'sonHafta'                  => 'Son Hafta',
    'sonAy'                     => 'Son Ay',
    'son6Ay'                    => 'Son 6 Ay',
    'sonYil'                    => 'Son Yıl',
    // kullanicilar
    'kullaniciAra'              => 'Kullanıcı Ara',
    'kNo'                       => 'Kullanıcı No',
    'kAdi'                      => 'Kullanıcı Adı',
    'kIsi'                      => 'Departmanı',
    'aktifPasif'                => 'Aktif/Pasif',
    'sonGirisTarihi'            => 'Son Giriş Tarihi',
    'aktif'                     => 'Aktif',
    'pasif'                     => 'Pasif',
    'ad'                        => 'Adi',
    'soyAd'                     => 'Soyadi',
    'isi'                       => 'Departmanı',
    'sifreTekrar'               => 'Şifre Tekrar',
    'kullaniciEklendi'          => ' Kullanıcı Ekledi',
    'yonetici'                  => 'Yönetici',
          // hatalar
    'AdiBosveya4tenfazlaYok'    => 'Adı boş veya Karakter Sayısı 4\'ten Az olmamalı',
    'sAdiBosveya4tenfazlaYok'   => 'Soyadı boş veya Karakter Sayısı 4\'ten Az olmamalı',
    'kAdiBosveya5tenfazlaYok'   => 'Kullanıcı Adı boş veya Karakter Sayısı 5\'ten Az olmamalı',
    'departmanBos'              => 'Departmanı Boş Olmamalı',
    'sifreEsitYok'              => 'Şifre Birbirine Eşit Olmalı',
    'buKDahaOnceKullanildi'     => 'Bu Kullanıcı Adı Daha Önce Kullanıldı',
    'kullaniciSilindi'          => ' Kullanıcı Silindi',
    'kullaniciGuncellendi'      => ' Kullanıcı Güncellendi',
    // Anasayfa
    'gununSatisToplamiTl'       => 'Günün Satışları Toplam TL',
    'depodaUrunSayisi'          => 'Depoda Ürün Sayısı',
    'satilanUrunSayisi'         => 'Bugün Satılan Ürün Sayısı',
    'enCokSatilanlar'           => 'En Çok Satılan',
    'sonSatislar'               => 'Son Satışlar',
    'yeniEklenenUrunler'        => 'Yeni Eklenen Ürünler',
  );
  return $arr[$lang];
}
